<a href="https://colab.research.google.com/github/M0On1260/skills-introduction-to-github/blob/main/pytorch00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [2]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.item()
#get number out of tensor

7

In [4]:
scaler.ndim

0

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
#matrix
matrix = torch.tensor([[1,2],
                     [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TENSOR[0,0,2]

tensor(3)

In [14]:
random_tensor = torch.rand(size=(5,5))
random_tensor,random_tensor.dtype

(tensor([[0.5062, 0.5618, 0.8599, 0.3811, 0.2645],
         [0.0134, 0.6501, 0.6733, 0.6117, 0.1670],
         [0.4546, 0.1786, 0.8225, 0.6807, 0.9426],
         [0.0137, 0.8359, 0.3536, 0.4941, 0.4920],
         [0.9765, 0.7970, 0.5795, 0.0607, 0.6593]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
one_to_ten = torch.arange(start=1,end=11,step=2)
one_to_ten


tensor([1, 3, 5, 7, 9])

In [17]:
zero = torch.zeros_like(one_to_ten)
zero

tensor([0, 0, 0, 0, 0])

In [18]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device



(torch.Size([3]), torch.float32, device(type='cpu'))

In [19]:
tensor = torch.tensor([1,2,3])
torch.multiply(tensor,100000)


tensor([100000, 200000, 300000])

In [20]:
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [21]:
torch.matmul(tensor,tensor)

tensor(14)

In [22]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[1.1417, 0.7652],
        [0.7459, 0.5506]])

In [23]:
tensor_A = torch.tensor(([[1,2],
                        [2,3],
                        [4,5]]),dtype=torch.float32)
tensor_B = torch.tensor(([[5,6],
                         [7,8],
                         [9,10]]),dtype=torch.float32)
torch.matmul(tensor_A,tensor_B.T)

tensor([[17., 23., 29.],
        [28., 38., 48.],
        [50., 68., 86.]])

finding the min,max,mean,sum,etc(tensor aggregatioon)


In [24]:
x=torch.arange(0,100,10)


In [25]:
#find the min
x.min()

tensor(0)

In [26]:
#find the max
x.max()

tensor(90)

In [27]:
#find the mean(can't have long float either a floating point or complez dtypes)
#note: torch.mean() function requires a tensor of float32 datatype to work
x.type(torch.float32).mean()
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()


tensor(45.)

In [28]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [29]:
x.argmin()
#find the position in ternsot that has min value and returns the value of index where min value occurs

tensor(0)

In [30]:
x.argmax()

tensor(9)

## reshaping,stacking,squeezing and unsqueezing tensors
#reshapes - reshaped an input tensor to a defined shape
#view-return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
#stacking - combine multiple tensors on top of each other(vstack) or side by side (hstack)
#squeeze - remove all '1' dimensions from a tensor
#unsqueeze - ass a '1' dimension to a target tensor
#permute - retuen a view of the input with dimensions permuted(swapped) in a certain way

In [31]:
 #let's create a tensor
 import torch
 x= torch.arange(1,10)
 x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [32]:
#add an extra dimension
x_reshaped = x.reshape(1,9) #5*2= 10  (10 elements)
x_reshaped,x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [33]:
#change the view
z = x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [34]:
#changing z chnaged x (cuz a view of a tensor shares the same memory as the orginal)
z[:0] = 5
z,x

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [35]:
#stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [36]:
#stack tensors on top of each other
x_stacked = torch.hstack([x,x,x,x])
x_stacked

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6,
        7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
#stack tensors on top of each other
x_stacked = torch.vstack([x,x,x,x])
x_stacked

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [38]:
x_squeeze = x_reshaped.squeeze()

In [39]:
#removes single dimension
x_squeeze = x_reshaped.squeeze()
x_squeeze
print(f"previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")
print(f"new tensor:{x_squeeze}")
print(f"new shape:{x_squeeze.shape}")

previous tensor:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
previous shape:torch.Size([1, 9])
new tensor:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
new shape:torch.Size([9])


In [40]:
#torch>unsqueeze()- adds a single dimension to a target tensor at a specfic dimension
print(f"previous target:{x_squeeze}")
print(f"previous shape:{x_squeeze.shape}")
x_unsqueeze=x_squeeze.unsqueeze(dim=1)
print(f"new target:{x_unsqueeze}")
print(f"new shape:{x_unsqueeze.shape}")

previous target:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape:torch.Size([9])
new target:tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
new shape:torch.Size([9, 1])


In [41]:
#torch>unsqueeze()- adds a single dimension to a target tensor at a specfic dimension
print(f"previous target:{x_squeeze}")
print(f"previous shape:{x_squeeze.shape}")
x_unsqueeze=x_squeeze.unsqueeze(dim=0)
print(f"new target:{x_unsqueeze}")
print(f"new shape:{x_unsqueeze.shape}")

previous target:tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
previous shape:torch.Size([9])
new target:tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
new shape:torch.Size([1, 9])


In [42]:
#torch.permute - rearranges the dimension of a target tensor in specified order
x_orginal = torch.rand(2,3,9)
x_orginal.size()
torch.permute(x_orginal,(1,0,2)).size()
#more like rearrange size


torch.Size([3, 2, 9])

In [43]:
x_real = torch.rand(224,224,3)
x_permuted = x_real.permute(2,0,1)
x_real.shape,x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [44]:
x_orginal[0,0,0] = 6872309
x_orginal[0,0,0],x_permuted[0,0,0]
#orginal and permuted have same data


(tensor(6872309.), tensor(0.5909))

In [46]:
#indexing(selecting data from tensors )
#indexing with pytorch is similar to indexing with Numpy


In [49]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [50]:
#let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [51]:
#index on middle bracket(dim=1)
x[0][0]

tensor([1, 2, 3])

In [56]:
#index on most inner bracket(last dim)
x[0][2][2]

tensor(9)

In [59]:
#your can alos use ":" to select "all" target dimension
x[:,2]

tensor([[7, 8, 9]])

In [60]:
#get all values of 0th and 1st deim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [61]:
#get all values of the 0 dim but only the 1 index value of 1st and 2nd dim
x[:,1,1]

tensor([5])

In [ ]:
#get the index 0 of 0th and 1st dim and all values of 2nd dim

In [62]:
#index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

In [ ]:
##pytorch tensors and numpy
#numpy is a popular scientific python numerical computing torch.library
#and because of this pytorch has functionality to interact with it.
#* data in numpy want in pytorch tensor - . 'torch.from_numpy(ndarray)'
#* pytorch tensor -> numpy - torch.Tensor.numpy()


In [65]:
#numpy array to tensor
import torch
import numpy as np
array = np.arange(1,10,1)
tensor = torch.from_numpy(array)#warning when converting from numpy,pytorch reflects numpy's defualt datatypes of float64 unless specified otherwise
array,tensor
nump = torch.Tensor.numpy(tensor)
nump
#defualt numpy dtype is float64

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
#change the value of array,what will this do to 'tensor'
array = array + 1
array,tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [67]:
#change the tensor,what will happen to array
tensor = tensor + 1
array,tensor
#if tensor changed array changes


(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
#reproducibility(trying to take random out of random)
#in short how a neural network learns:
#start with random numbers -> tesnor operations -> update randomnumbers to try and make them better representations of the date->again and again
#to reduce the randomness in neural networks and pytorch comes the concept of a **random seed** what random seed does is flavour the randomness.

In [68]:
import torch
random_tensor_A = torch.rand(3,3)


tensor([[0.0083, 0.0678, 0.2586],
        [0.3129, 0.4375, 0.1148],
        [0.4593, 0.0519, 0.6855]])

In [76]:
import torch
#create two random tensors
random_tensor_A = torch.rand(3,3)
random_tensor_B = torch.rand(3,3)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2671, 0.4076, 0.9037],
        [0.5849, 0.6736, 0.3942],
        [0.7318, 0.1276, 0.3011]])
tensor([[0.0805, 0.4898, 0.1194],
        [0.3517, 0.2974, 0.4132],
        [0.5421, 0.4859, 0.8697]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [80]:
#let's make some random but reporducible tensors
import torch
#set the random drr
RANDOM_SEED = 34
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,3)
torch.manual_seed(RANDOM_SEED)
random_tensor_E = torch.rand(3,3)
print(random_tensor_D)
print(random_tensor_E)
print(random_tensor_D == random_tensor_E)



tensor([[0.8718, 0.1155, 0.7057],
        [0.3841, 0.7322, 0.0119],
        [0.0205, 0.6273, 0.5561]])
tensor([[0.8718, 0.1155, 0.7057],
        [0.3841, 0.7322, 0.0119],
        [0.0205, 0.6273, 0.5561]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


In [ ]:
 ##running tensors and pytorch objects on the gpus(and making faster computations)


In [1]:
#check for gpu access with pytorch
import torch
torch.cuda.is_available()


False